---
title: "COVID-19 Belgium Notebook"
output:
  html_document:
    df_print: paged
  html_notebook: default
---

# Data

https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_time_series

and

https://github.com/eschnou/covid19-be

We hope we'll soon get proper data from

https://epistat.wiv-isp.be/covid/

Data is now available (31/3/2020)

# Code

Code for the charts is available at https://github.com/philippeback/COVID-19/



```{r Sources, echo=FALSE}
sourceConfirmed <- "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv"

sourceDeceased <- "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv"

sourceRecovered <- "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_recovered_global.csv"

sourceEschnou <- "https://raw.githubusercontent.com/eschnou/covid19-be/master/covid19-belgium.csv"

sourceSciensanoHospitalized <- "https://epistat.sciensano.be/Data/COVID19BE_HOSP.csv"
```


```{r Read Source JH, echo=FALSE, warning=FALSE, error=FALSE}

require(lubridate)
#require(glue)

dataConfirmed <- read.csv(sourceConfirmed)

dataDeceased <- read.csv(sourceDeceased)

dataRecovered <- read.csv(sourceRecovered)


#print(str(dataConfirmed))
#print(str(dataDeceased))
#print(str(dataRecovered))

```

```{r Read Source Eschnou, echo=FALSE, warning=FALSE}

# Damn UTF-8 BOM...
dataEschnou <- read.csv(sourceEschnou, fileEncoding = "UTF-8-BOM")
# print(str(dataEschnou))

belgiumLatest<-tail(dataEschnou,1)
parsedDate<-parse_date_time(as.character(belgiumLatest$date),c("dmy"))
belgiumLatestDate<-gsub("#0", "", format(parsedDate,"X#%m.%d.%y"))

latestBelgiumColumnConfirmed<-data.frame(belgiumLatest$cumul_cases)
names(latestBelgiumColumnConfirmed)[1] <- belgiumLatestDate

latestBelgiumColumnDeceased<-data.frame(belgiumLatest$cumul_deceased)
names(latestBelgiumColumnDeceased)[1] <- belgiumLatestDate

latestBelgiumColumnRecovered<-data.frame(belgiumLatest$cumul_released)
names(latestBelgiumColumnRecovered)[1] <- belgiumLatestDate


```

```{r Read Source Sciensano}

dataSciensanoHospitalized <- read.csv(sourceSciensanoHospitalized)
```

```{r comment='', echo=FALSE, results='asis'}
#knitr::kable(dataSciensanoHospitalized, caption = "Hospitalized Official", floating.environment="sidewaystable")
```


```{r echo=FALSE}

country="Belgium"
#country="Netherlands"

dataPointsOfCountry <- function(rawDataset, countryName) {
  dataOfCountry <- rawDataset[rawDataset$Country.Region == country, ]
  dataPointsOfCountry <-  dataOfCountry[,c(5:ncol(dataOfCountry))]
  return(dataPointsOfCountry)
}
  
  
dataPointsConfirmed <- dataPointsOfCountry(dataConfirmed, country)
dataPointsDeceased <-  dataPointsOfCountry(dataDeceased, country)
dataPointsRecovered <- dataPointsOfCountry(dataRecovered, country)


if (country=="Belgium") {
  dataPointsConfirmed <- cbind(dataPointsConfirmed,latestBelgiumColumnConfirmed)
  dataPointsDeceased <- cbind(dataPointsDeceased,latestBelgiumColumnDeceased)
  dataPointsRecovered <- cbind(dataPointsRecovered,latestBelgiumColumnRecovered)
}


cleanDate <- function(s) {
   p<-unlist(strsplit(s,"X|\\."))
   return(paste0(p[3],"/",p[2],"/20",p[4]))
}

```

# Figures

## Linear Figures

```{r Confirmed, echo=FALSE, error=TRUE}

ymax <- max(dataPointsConfirmed)
yrange <- c(0, (floor(ymax/1000.0)+1)*1000)
xvalues <- seq_along(dataPointsConfirmed)

plot(
  xvalues,
  dataPointsConfirmed, 
  xlab="days since 22/1/2020", 
  ylab="confirmed cases", 
  main=paste0(
    country, 
    " confirmed COVID-19 cases on ",
    cleanDate(tail(names(dataPointsConfirmed),1))),
  type="l",
  lwd=2,
  col="dark green",
  ylim=yrange)

abline(h=ymax, col="dark green", lty=4)
text(
  tail(xvalues,1)*0.95,
  (ymax * 1.03),
  paste("Max:",ymax),
  cex=0.6)
```


```{r Deceased, echo=FALSE, error=TRUE, message=TRUE, warning=TRUE}
plot(seq_along(dataPointsDeceased),dataPointsDeceased, xlab="days since 22/1/2020", ylab="deceased cases", main=paste0(country," deceased COVID-19 cases on ",cleanDate(tail(names(dataPointsDeceased),1))),type="l",col="dark red",lwd=2)
```
```{r Recovered, echo=FALSE, error=TRUE, message=TRUE, warning=TRUE}
plot(seq_along(dataPointsRecovered),dataPointsRecovered, xlab="days since 22/1/2020", ylab="recovered cases", main=paste0(country," recovered COVID-19 cases on ",cleanDate(tail(names(dataPointsRecovered),1))),type="l",col="orange",lwd=2)
```

## Logarithmic Figures

```{r Confirmed Log, echo=FALSE, error=TRUE}

plot(seq_along(dataPointsConfirmed),log(dataPointsConfirmed), xlab="days since 22/1/2020", ylab="log(confirmed cases)", main=paste0(country, " confirmed COVID-19 cases on ",cleanDate(tail(names(dataPointsConfirmed),1))),type="l",col="dark green",lwd=2)


```


```{r Deceased Log, echo=FALSE, error=TRUE}
plot(seq_along(dataPointsDeceased),log(dataPointsDeceased), xlab="days since 22/1/2020", ylab="log(deceased cases)", main=paste0(country, " deceased COVID-19 cases on ",cleanDate(tail(names(dataPointsDeceased),1))),type="l",col="dark red",lwd=2)
```


```{r Recovered Log, echo=FALSE, error=TRUE}
plot(seq_along(dataPointsRecovered),log(dataPointsRecovered), xlab="days since 22/1/2020", ylab="log(recovered cases)", main=paste0(country, " recovered COVID-19 cases on ",cleanDate(tail(names(dataPointsRecovered),1))),type="l",col="orange",lwd=2)
```

# Curve fit

## Data Prep
```{r Transpose, echo=TRUE, message=TRUE, warning=TRUE}
library(data.table)
df<-transpose(dataPointsConfirmed)
df<-cbind(df,seq_along(dataPointsConfirmed))
names(df)<-c("total","day")
plot(total~day,data=df)
```

## Work on usable part of the dataset

```{r message=TRUE, warning=TRUE}
df2<- df[25:nrow(df),]
head(df2,3)
```

## Initial fit parameters for SSlogis

```{r message=TRUE, warning=TRUE}
# Get initial estimate
SS<-getInitial(total~SSlogis(day,alpha,xmid,scale),data=tail(df2,40),trace=TRUE)
```

## Fitting model

```{r message=TRUE, warning=TRUE}
fit<-nls(total~SSlogis(day,alpha,xmid,scale),data=df2)
summary(fit)
```
## Goodness of fit estimate
```{r}
cor(df2$total,predict(fit))
```

```{r}
require(nlstools)
res<-nlsResiduals(fit)
plot(res,which=0)
```
```{r}
plot(res, which = 3)
```


```{r}
plot(res, which = 5)
```


```{r}
plot(res, which = 6)
```

```{r}
test.nlsResiduals(res)
```


## Predict data



## Plot curve

```{r}
x=seq(0,100,1)
y=seq(0,100,1)
plot(x,y,
     xlim=c(0,200),
     ylim=c(0,31000),
     xlab="days",
     ylab="cases",
     type="n",
     main="Prediction of cases")

ypred <- predict(fit,list(day=x))
ypred_max <- max(ypred)

points(total~day,data=df2)
abline(h=ypred_max,lty=2)
text(x=100,y=ypred_max*1.04,paste0("max=",format(ypred_max,digits=0,scientific = FALSE)))
lines(x,ypred,col="dark green",lty=1,lwd=3)
```
# Sciensano ICU 

```{r}
totalICU <- dataSciensanoHospitalized %>% group_by(DATE) %>%summarize(TOTAL_IN_ICU = sum(TOTAL_IN_ICU))

plot(TOTAL_IN_ICU ~ DATE,data=totalICU,type="p",main="Total in ICU Belgium")
```
# Sciensano in RESP

```{r}
totalRESP <- dataSciensanoHospitalized %>% group_by(DATE) %>%summarize(TOTAL_IN_RESP = sum(TOTAL_IN_RESP))

plot(TOTAL_IN_RESP ~ DATE,data=totalRESP,type="p",main="Total in RESP Belgium")
```

# Sciensano ECMO

```{r}
totalECMO <- dataSciensanoHospitalized %>% group_by(DATE) %>%summarize(TOTAL_IN_ECMO = sum(TOTAL_IN_ECMO))

plot(TOTAL_IN_ECMO ~ DATE,data=totalECMO,type="p",main="Total in ECMO Belgium")
```

# Links

* https://www.statforbiology.com/nonlinearregression/usefulequations
* https://www.r-bloggers.com/first-steps-with-non-linear-regression-in-r
  


